[tools]
"rust" = "1.80.0"
"cargo:espup" = "0.12.2"
"cargo:espflash" = "3.1.1"

[tasks.init]
# chicken and egg thing, can't set the esp toolchain until after espup
# is installed. so use the default to install espup + espflash, then set
run = "espup install -t esp32s3 && cp rust-toolchain.example.toml rust-toolchain.toml"
