[tools]
rust = "latest"
"cargo:espup" = "0.15.0"
"cargo:espflash" = "3.3.0"
"cargo:cargo-groups" = "0.1.9"

[tasks.init]
# chicken and egg thing, can't set the esp toolchain until after espup
# is installed. so use the default to install espup + espflash, then set
run = "espup install -t esp32s3 && cp rust-toolchain.example.toml rust-toolchain.toml"
