[build]
target = "xtensa-esp32s3-espidf"
rustflags = [
    "-C",
    "link-arg=-nostartfiles",
    "-C",
    "link-arg=-Wl,-Tlinkall.x",
    "-C",
    "link-arg=-Trom_functions.x",
    "-C",
    "link-arg=-Tdefmt.x",
    "-C",
    "force-frame-pointers",
]

[target.'cfg(target_arch = "xtensa")']
runner = "espflash flash --monitor --log-format defmt"

[unstable]
build-std = ["core"]

# set env
[env]
DEFMT_LOG = "info"
